flags: {}
packages:
- '.'
- examples/hello-world
- examples/subsites
- examples/blaze-html
- examples/shakespeare
- examples/rest-json
- examples/streaming-response
- examples/kitchen
- examples/unrouted
- examples/bare-wai
extra-deps:
- aeson-1.2.0.0
resolver: lts-8.11
